name: 'Run Tests'
description: 'Run Tests'
inputs:
  test_selection:
    description: 'Positional Argument for stestr run'
    default: ""
    required: false
  repo_install_command:
    description: 'Optional command to run for installing repository under test'
    default: "pip install ."
    required: false
runs:
  using: "composite"
  steps:
    - name: Clone Qiskit/qiskit-neko PUBLIC repository
      uses: actions/checkout@v3
      with:
        repository: Qiskit/qiskit-neko
        path: qiskit-neko
    - name: Access cloned repository content
      run: |
        cd qiskit-neko
      shell: bash
    - name: Download Released Dependencies
      run: |
        pip install .
        cd ..
      shell: bash
    - name: Checkout base repository
      uses: actions/checkout@v3
    - name: Install repo under test
      run: |
        ${{ inputs.repo_install_command }}
      shell: bash
    - name: Run Unit Tests
      env:
        PYTHONWARNINGS: default
      run: |
        cd qiskit-neko
        stestr run ${{ inputs.test_selection }}
      shell: bash
