name: 'Run Tests'
description: 'Run Tests'
inputs:
  test_selection:
    description: 'Positional Argument for stestr run'
    default: ""
    required: false
  repo_install_command:
    description: 'Optional command to run for installing repository under test'
    default: "pip install ."
    required: false
runs:
  using: "composite"
  steps:
    - name: Clone Qiskit/qiskit-neko PUBLIC repository
      uses: actions/checkout@v4
      with:
        repository: Qiskit/qiskit-neko
        path: qiskit-neko
    - name: Update setuptools and pip
      run: |
        pip install -U setuptools pip
      shell: bash
    - name: Install neko and its dependencies
      run: |
        pip install ./qiskit-neko
      shell: bash
    - name: Checkout base repository
      uses: actions/checkout@v4
      with:
        path: repo_under_test
    - name: Install repo under test
      run: |
        set -e
        pushd repo_under_test
        ${{ inputs.repo_install_command }}
        popd
      shell: bash
    - name: Run Unit Tests
      env:
        PYTHONWARNINGS: default
      run: |
        set -e
        cd qiskit-neko
        stestr run ${{ inputs.test_selection }}
      shell: bash
