name: 'Run Tests'
description: 'Run Tests'
inputs:
  test_selection:
    description: 'Positional Argument for stestr run'
    default: ""
    required: false
runs:
  using: "composite"
  steps:
    - name: Clone mtreinish/qiskit-neko PUBLIC repository
      uses: mtreinish/clone-github-repo-action@v2
      with:
        owner: 'mtreinish'
        repository: 'qiskit-neko'
    - name: Access cloned repository content
      run: |
        cd qiskit-neko
    - name: Download Released Dependencies
      run: |
        pip install .
        cd ..
    - name: Checkout base repository
      uses: actions/checkout@v3   
    - name: Run Unit Tests
      env:
        PYTHONWARNINGS: default
      run: |
        cd qiskit-neko
        stestr run ${{ inputs.test_selection }}
      shell: bash